// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "goproxy/server/models"
)

// GetAccounts2Reader is a Reader for the GetAccounts2 structure.
type GetAccounts2Reader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccounts2Reader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAccounts2OK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetAccounts2BadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetAccounts2Default(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAccounts2OK creates a GetAccounts2OK with default headers values
func NewGetAccounts2OK() *GetAccounts2OK {
	return &GetAccounts2OK{}
}

/*GetAccounts2OK handles this case with default header values.

A list of records
*/
type GetAccounts2OK struct {
	Payload models.GetAccounts2OKBody
}

func (o *GetAccounts2OK) Error() string {
	return fmt.Sprintf("[GET /accounts2][%d] getAccounts2OK  %+v", 200, o.Payload)
}

func (o *GetAccounts2OK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccounts2BadRequest creates a GetAccounts2BadRequest with default headers values
func NewGetAccounts2BadRequest() *GetAccounts2BadRequest {
	return &GetAccounts2BadRequest{}
}

/*GetAccounts2BadRequest handles this case with default header values.

Record not found
*/
type GetAccounts2BadRequest struct {
}

func (o *GetAccounts2BadRequest) Error() string {
	return fmt.Sprintf("[GET /accounts2][%d] getAccounts2BadRequest ", 400)
}

func (o *GetAccounts2BadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetAccounts2Default creates a GetAccounts2Default with default headers values
func NewGetAccounts2Default(code int) *GetAccounts2Default {
	return &GetAccounts2Default{
		_statusCode: code,
	}
}

/*GetAccounts2Default handles this case with default header values.

Sorry something went wrong
*/
type GetAccounts2Default struct {
	_statusCode int
}

// Code gets the status code for the get accounts2 default response
func (o *GetAccounts2Default) Code() int {
	return o._statusCode
}

func (o *GetAccounts2Default) Error() string {
	return fmt.Sprintf("[GET /accounts2][%d] GetAccounts2 default ", o._statusCode)
}

func (o *GetAccounts2Default) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
