// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetAccounts2Params creates a new GetAccounts2Params object
// with the default values initialized.
func NewGetAccounts2Params() *GetAccounts2Params {
	var ()
	return &GetAccounts2Params{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetAccounts2ParamsWithTimeout creates a new GetAccounts2Params object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetAccounts2ParamsWithTimeout(timeout time.Duration) *GetAccounts2Params {
	var ()
	return &GetAccounts2Params{

		timeout: timeout,
	}
}

// NewGetAccounts2ParamsWithContext creates a new GetAccounts2Params object
// with the default values initialized, and the ability to set a context for a request
func NewGetAccounts2ParamsWithContext(ctx context.Context) *GetAccounts2Params {
	var ()
	return &GetAccounts2Params{

		Context: ctx,
	}
}

// NewGetAccounts2ParamsWithHTTPClient creates a new GetAccounts2Params object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetAccounts2ParamsWithHTTPClient(client *http.Client) *GetAccounts2Params {
	var ()
	return &GetAccounts2Params{
		HTTPClient: client,
	}
}

/*GetAccounts2Params contains all the parameters to send to the API endpoint
for the get accounts2 operation typically these are written to a http.Request
*/
type GetAccounts2Params struct {

	/*ID
	  PK

	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get accounts2 params
func (o *GetAccounts2Params) WithTimeout(timeout time.Duration) *GetAccounts2Params {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get accounts2 params
func (o *GetAccounts2Params) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get accounts2 params
func (o *GetAccounts2Params) WithContext(ctx context.Context) *GetAccounts2Params {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get accounts2 params
func (o *GetAccounts2Params) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get accounts2 params
func (o *GetAccounts2Params) WithHTTPClient(client *http.Client) *GetAccounts2Params {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get accounts2 params
func (o *GetAccounts2Params) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the get accounts2 params
func (o *GetAccounts2Params) WithID(id int32) *GetAccounts2Params {
	o.SetID(id)
	return o
}

// SetID adds the id to the get accounts2 params
func (o *GetAccounts2Params) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GetAccounts2Params) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param id
	qrID := o.ID
	qID := swag.FormatInt32(qrID)
	if qID != "" {
		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
