swagger: '2.0'

info:
  version: 1.0.0
  title: Simple API
  description: A simple API to learn how to write OpenAPI Specification
schemes:
  - http
host: localhost:5000
basePath: /v1
paths:
  /accounts2:
    get:
      summary: Gets some accounts
      description: Returns a list containing all accounts2.
      parameters:
        - name: id
          in: query
          description: PK
          required: true
          type: integer
          format: int32
      responses:
        200:
          description: A list of records
          schema:
            type: array
            items:
              required:
                - id
                - name
              properties:
                 id:
                   type: integer
                 name:
                   type: string
        400 :
          description: Record not found
        default:
          description: Sorry something went wrong
